name: Sync Issues to JIRA

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  update:
    name: Update Issue
    uses: canonical/sdcore-github-workflows/.github/workflows/issues.yaml@dev-build
    secrets:
      JIRA_URL: ${{ secrets.JIRA_URL }}
