name: Main branch CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 0'

jobs:
  codeql:
    name: CodeQL Analysis
    uses: canonical/sdcore-github-workflows/.github/workflows/codeql-analysis.yml@v2.3.3

  check-libraries:
    uses: canonical/sdcore-github-workflows/.github/workflows/check-libraries.yaml@v2.3.3
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  lint-report:
    uses: canonical/sdcore-github-workflows/.github/workflows/lint-report.yaml@v2.3.3

  terraform-check:
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@v2.3.3

  static-analysis:
    uses: canonical/sdcore-github-workflows/.github/workflows/static-analysis.yaml@v2.3.3

  unit-tests-with-coverage:
    uses: canonical/sdcore-github-workflows/.github/workflows/unit-test.yaml@v2.3.3

  build:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
    uses: canonical/sdcore-github-workflows/.github/workflows/build.yaml@v2.3.3
    secrets: inherit

  integration-test:
    needs:
      - build
    uses: canonical/sdcore-github-workflows/.github/workflows/integration-test.yaml@add-jhack-snap
    with:
      enable-metallb: true

  publish-charm:
    name: Publish Charm
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ github.ref_name == 'main' }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@v2.3.3
    with:
      track-name: 1.6
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  publish-charm-on-push:
    name: Publish Developer Charm To Branch
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ (github.ref_name != 'main') && (github.event_name == 'push') }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@v2.3.3
    with:
      branch-name: ${{ github.ref_name }}
      track-name: 1.6
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  lib-needs-publishing:
    runs-on: ubuntu-24.04
    outputs:
      needs-publishing: ${{ steps.changes.outputs.fiveg_n2 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            fiveg_n2:
              - 'lib/charms/sdcore_amf_k8s/v0/fiveg_n2.py'

  publish-lib:
    name: Publish Lib
    needs:
      - publish-charm
      - lib-needs-publishing
    if: ${{ github.ref_name == 'main' }} && ${{ needs.changes.outputs.needs-publishing == 'true' }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-lib.yaml@v2.3.3
    with:
      lib-name: "charms.sdcore_amf_k8s.v0.fiveg_n2"
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
